# Generated by Django 2.2.3 on 2020-02-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Aluno Ativo'),
        ),
    ]

