# Generated by Django 2.2.3 on 2020-02-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_aluno_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Aluno Ativo'),
        ),
    ]
