# Generated by Django 2.1.1 on 2018-11-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sige', models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='Matricula do SIGE')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('serie', models.IntegerField(choices=[(1, '1 Série'), (2, '2 Série'), (3, '3 Série')], default=1, verbose_name='Numero da série')),
                ('turma', models.CharField(choices=[('A', 'TURMA A'), ('B', 'TURMA B'), ('C', 'TURMA C'), ('D', 'TURMA D')], default='A', max_length=1, verbose_name='Turma ')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
            ],
        ),
    ]
