# Generated by Django 2.1.1 on 2018-11-20 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_registroeletiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroeletiva',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 20, 1, 22, 585639), verbose_name='Data de criação'),
        ),
    ]
