# Generated by Django 2.1.1 on 2018-11-21 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_registroeletiva_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroeletiva',
            name='ativo',
            field=models.IntegerField(choices=[('Sim', 1), ('Não', 0)], default=1, verbose_name='A eletiva está ativada'),
        ),
        migrations.AlterField(
            model_name='registroeletiva',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 21, 8, 15, 1, 26704), verbose_name='Data de criação'),
        ),
    ]
