# Generated by Django 2.2.3 on 2019-07-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sige', models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='Matricula do SIGE')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('serie', models.IntegerField(choices=[(1, '1 Série'), (2, '2 Série'), (3, '3 Série')], default=1, verbose_name='Numero da série')),
                ('turma', models.CharField(choices=[('A', 'TURMA A'), ('B', 'TURMA B'), ('C', 'TURMA C'), ('D', 'TURMA D')], default='A', max_length=1, verbose_name='Turma')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Eletiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Codigo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('responsavel', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome do Responsável')),
                ('vagas', models.IntegerField(default=32, verbose_name='Número disponível de vagas')),
                ('vagas_usadas', models.IntegerField(default=0, verbose_name='Vagas_preenchidas')),
                ('dia', models.CharField(choices=[('0', 'Dia não definido'), ('1', 'Segunda'), ('2', 'Terça'), ('3', 'Quarta'), ('4', 'Quinta'), ('5', 'Sexta')], default='0', max_length=1, verbose_name='Dia da eletiva')),
                ('periodo', models.CharField(choices=[('0', 'Turno não definido'), ('1', 'Manhã'), ('2', 'Tarde')], default='0', max_length=1, verbose_name='Período da eletiva')),
                ('ativo', models.BooleanField(default=False, verbose_name='Eletiva está ativa')),
                ('ano', models.IntegerField(verbose_name='Ano da Eletiva')),
                ('semestre', models.IntegerField(choices=[(1, '1 semestre'), (2, '2 semestre')], verbose_name='Semestre da Eletiva')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
            options={
                'ordering': ['dia', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Registro ativo')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='gestao.Aluno')),
                ('eletiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='gestao.Eletiva')),
            ],
            options={
                'ordering': ['aluno__nome', 'aluno__serie', 'aluno__turma'],
            },
        ),
    ]
