# Generated by Django 2.2.3 on 2020-01-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_auto_20200107_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='eletiva',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Eletiva',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
