# Generated by Django 2.1.1 on 2018-11-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_auto_20181119_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='eletiva',
            name='vagas_usadas',
            field=models.IntegerField(default=0, verbose_name='Vagas_preenchidas (deixe zero!)'),
        ),
        migrations.AlterField(
            model_name='eletiva',
            name='desc',
            field=models.TextField(verbose_name='Descrição da eletiva'),
        ),
        migrations.AlterField(
            model_name='eletiva',
            name='dia',
            field=models.CharField(choices=[('1', 'Segunda'), ('2', 'Terça'), ('3', 'Quarta'), ('4', 'Quinta'), ('5', 'Sexta')], default='1', max_length=1, verbose_name='Dia da eletiva'),
        ),
        migrations.AlterField(
            model_name='eletiva',
            name='vagas',
            field=models.IntegerField(default=32, verbose_name='Número disponível de vagas'),
        ),
    ]
