# Generated by Django 2.1.1 on 2018-11-17 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eletiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('vagas', models.IntegerField(default=32, verbose_name='Numero disponivel de vagas')),
                ('desc', models.TextField(verbose_name='Descricao da Eletiva')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('disciplina', models.CharField(max_length=50, verbose_name='Disciplina')),
                ('sige', models.CharField(max_length=7, verbose_name='Matricula SIGE')),
                ('senha', models.CharField(max_length=80, verbose_name='Senha')),
            ],
        ),
        migrations.AddField(
            model_name='eletiva',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.Professor'),
        ),
    ]
