# Generated by Django 2.1.1 on 2018-11-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eletiva',
            name='dia',
            field=models.CharField(choices=[('1', 'segunda'), ('2', 'terça'), ('3', 'quarta'), ('4', 'quinta'), ('5', 'sexta')], default='1', max_length=1, verbose_name='Dia da eletiva'),
        ),
        migrations.AddField(
            model_name='eletiva',
            name='periodo',
            field=models.CharField(choices=[('1', 'Manhã'), ('2', 'Tarde')], default='1', max_length=1, verbose_name='Período da eletiva'),
        ),
    ]
